### ISSUE TITLE
perl code size limits / code blocks using modules 

### ISSUE THREAD

**Issue by darked89** [wavexx/python-bond#1]
Hello,

my problem: 
I have +2k lines in a buggy/broken Perl script and +0.5k in hopefully more sane modules. I can get rid of things like Getopt::Long, Cwd by doing it in Python and hopefully passing these to extracted old Perl code as needed using python_bond. 
I have to stress that the Perl code is really bad. Replacing as much as possible with Python easier for me to validate the intermediate results and comprehend the functionality.  

Hence my question(s):
1. Do you think that python-bond is a good choice for this purpose (=mixed Python/Perl code for refactoring)?
2. If yes, can Perl blocks use custom Perl libs? 

Many thanks for your help

Darek

**Comment by wavexx** [comment]
I regularly do this, so yes. I've a much larger projects binding to Perl's EnsEMBL modules for example.

If your perl code is as bad as it sounds, it's probably going to use a lot of global state (speaking of experience...). ref() will help in this scenario, but might not make the code more readable.

As usual, binding python to bad code will not make it magically better.

What you really want to do, and which helps tremendously, is write some dumb tests before starting the conversion. Just some known input/outputs which are compared with a shell script will do.

This will let you know if you're destroying references in nested structures you're not aware of.

**Comment by darked89** [comment]
Thank you, this should keep me going :). 
This Perl script (say oldx_1.pl) has a number of hardwired constants, so simply getting them out, storing in YAML and using Python to parse them will make things a bit more sane. The bad thing is that I can not simply try to translate few lines or recreate all the intermediate data structures of the old script because "(really) big mistakes were made". 
I need to rethink what I can test in this situation.

**Comment by wavexx** [comment]
I could write a book on rewriting bad code.. ;)

The key thing is that it's generally always better to do an incremental translation. For example, if data structures are beyond repair, it's generally better to use a sane, *second* set of structures along the way (even if they contain partial data, or full redundant copies).

Code might look dirtier in the beginning, but you can migrate chunks bit by bit, without having to rewrite all functions that make use of the data structure.

I cannot stress enough the need for tests in these situations. There is no need for fancy frameworks, this is first and foremost to help you know what's breaking. If you were to keep the code in Perl, it would be one thing, but references are nasty across the python/perl bridge. They would decode properly in python, but fail to reconstruct the same on the way back, for example (with references to arrays now being just arrays).

With modern perl code and auto-deferencing you could make code that works correctly in both cases, but for old perl this might introduce even more bugs.

**Comment by darked89** [comment]
The original Perl script (lets call it xyz_precalc.pl) does work wobblingly with Perl 5.10. At least starting from perl 5.18 it breaks. I got  a bit improved & simplified version (more sane variable names, debug statements, extensive commenting out optional execution paths). This one "almost" works with perl 5.20/5.22 but hunting the bug stopping it is costly. Both versions use equally ancient used only in-house C-coded programs crashing on larger inputs. I got also a handful of AWK scripts invoked by the main program, and tens of lines with system commands, often in a form of pipes failing silently. Then there is a sorting of intermediate results values with custom sorting patterns, i.e. (cut @2 lines for saving space):
    $b->[13] <=> $a->[13]
    $b->[6]  <=> $a->[6]

In the end the program produces text file in its own format (16k lines). This one is luckily human readable. Whole file divided into 23 named sections (possible more when running the program with optional switches), some of them with subsections. Anything from a single 0 number to 3k of lines with columnar data. Handful of comments, and apparently only some parts are filled with input-dependent values. Reading/modifying/parsing this data format is handled by more sane looking Perl modules using OO. Running the original script with the same parameters/inputs produces almost identical but not quite output (some computations, possibly handled by external C-programs are apparently not deterministic). 
In the end the result (parameter file) is used/validated by downstream C-program (lets call it xyz_calc). As long as parameter file is properly formatted with not insane numerical values xyz_calc will produce results with various accuracy, using  the parameter file and the compatible input data set. 

For me the golden solution would be to hack/convince xyz_calc maintainers to dump IMHO pointless format and switch to i.e. YAML with a swarm of parsers. Switching into revolutionary rewrite mode, I should forget for time being about the parameter-file format handling Perl libs, use YAML to get the output faster/easier, then worry about translating YAML to xyzcalc-compatible format.

Well, this turned out into some over-caffeinated brainstorm-type post, but apparently trying to explain things turns on problem solving(?) mode in my head. Sorry for getting rather off-topic.   
 
BTW, the program which shall not be named yet deals with DNA/genomes.

**Comment by wavexx** [comment]
On 02/12/15 17:57, Darek K. wrote:
> For me the golden solution would be to hack/convince xyz_calc
> maintainers to dump IMHO pointless format and switch to i.e. YAML with a
> swarm of parsers. Switching into revolutionary rewrite mode, I should
> forget for time being about the parameter-file format handling Perl
> libs, use YAML to get the output faster/easier, then worry about
> translating YAML to xyzcalc-compatible format.

Parsing YAML is costly though. Speaking from experience, python-yaml is
orders of magnitude slower than JSON, even for small datasets (it
greatly depends on the indentation formats and the number of blocks in it).

> Well, this turned out into some over-caffeinated brainstorm-type post,
> but apparently trying to explain things turns on problem solving(?) mode
> in my head. Sorry for getting rather off-topic.
> 
> BTW, the program which shall not be named yet deals with DNA/genomes.

Aaah, pretty typical then ;).

The amount of punching that needs to be done, even for pretty popular
linkage/gwas analysis packages is mind-blowing.

There are bugs I've found in some packages (*cough* genehunter  *cough*)
reading matrices strait out of thin air (aka: uninitialized memory).
Makes you wonder about the results... really.

I almost wanted to start a blog about "bug fixes for popular yet
unmaintained genomic packages", but I realized I might get too much
backlash from the sci community.

Yet, after years, *very* few authors actually responded to my patch
submissions... I still wonder if I should do it...

**Comment by wavexx** [comment]
Should we leave this open so I can ping you on your progress? ;)

**Comment by wavexx** [comment]
Pinging @darked89 for progress(tm)
